<template>
  <a-form-model
    :label-col="{ span: 8 }"
    :wrapper-col="{ span: 12 }"
    ref="mailLetterEditForm"
    :rules="mailLetterEditFormRules"
  >
    <a-row>
      <a-col :span="8">
        <a-form-model-item
          :label="$t('noticeManualLetterForm_mailbyPostDate')"
          prop="mailByPostDate"
          style="margin-bottom: 0px"
          required
          :has-feedback="
            callCommonUtilFeildFeedback(
              mailLetterEditValidationForm.mailByPostDate
            )
          "
          :validateStatus="
            callCommonUtilFeildStatus(
              mailLetterEditValidationForm.mailByPostDate
            )
          "
        >
          <a-popover
            placement="top"
            :content="
              callCommonUtilFeildMsg(
                mailLetterEditValidationForm.mailByPostDate
              )
            "
            :trigger="
              callCommonUtilFeildTrigger(
                mailLetterEditValidationForm.mailByPostDate
              )
            "
            :visible="
              callCommonUtilFeildHoverVisible(
                mailLetterEditValidationForm.mailByPostDate
              )
            "
            @visibleChange="
              callCommonUtilFeildVisibleChange(
                mailLetterEditValidationForm.mailByPostDate
              )
            "
            :destroyTooltipOnHide="true"
          >
            <!-- 郵寄日期 -->
            <date-picker
              :formatter="formatter"
              @change="onMailPostDateChange"
              v-model="modifymailLetterForm.mailByPostDate"
              :range="false"
              style="width: 100%"
              :clearable="false"
              :disabled-date="disabledDate"
            >
              <a-input
                slot="input"
                :value="modifymailLetterForm.mailByPostDateString"
              ></a-input>
              <i
                v-if="mailLetterEditValidationForm.mailByPostDate.feedback"
                slot="icon-calendar"
              ></i>
            </date-picker>
          </a-popover>
        </a-form-model-item>
      </a-col>
      <a-col :span="12">
        <!-- 收件人 -->
        <a-form-model-item
          :label="$t('noticeManualLetterForm_receiver')"
          prop="receiver"
          style="margin-bottom: 0px"
          required
          :has-feedback="
            callCommonUtilFeildFeedback(mailLetterEditValidationForm.receiver)
          "
          :validateStatus="
            callCommonUtilFeildStatus(mailLetterEditValidationForm.receiver)
          "
        >
          <a-popover
            placement="top"
            :content="
              callCommonUtilFeildMsg(mailLetterEditValidationForm.receiver)
            "
            :trigger="
              callCommonUtilFeildTrigger(mailLetterEditValidationForm.receiver)
            "
            :visible="
              callCommonUtilFeildHoverVisible(
                mailLetterEditValidationForm.receiver
              )
            "
            @visibleChange="
              callCommonUtilFeildVisibleChange(
                mailLetterEditValidationForm.receiver
              )
            "
            :destroyTooltipOnHide="true"
          >
            <a-input
              type="text"
              v-model="modifymailLetterForm.receiver"
              :maxLength="100"
              @change="onSelectReceiver()"
            />
          </a-popover>
        </a-form-model-item>
      </a-col>
    </a-row>
    <a-row>
      <a-col :span="8">
        <!-- 郵寄地址type-->
        <a-form-model-item
          :label="$t('noticeManualLetterForm_address')"
          prop="addressType"
          style="margin-bottom: 0px"
          required
          :has-feedback="
            callCommonUtilFeildFeedback(
              mailLetterEditValidationForm.addressType
            )
          "
          :validateStatus="
            callCommonUtilFeildStatus(mailLetterEditValidationForm.addressType)
          "
        >
          <a-popover
            placement="top"
            :content="
              callCommonUtilFeildMsg(mailLetterEditValidationForm.addressType)
            "
            :trigger="
              callCommonUtilFeildTrigger(
                mailLetterEditValidationForm.addressType
              )
            "
            :visible="
              callCommonUtilFeildHoverVisible(
                mailLetterEditValidationForm.addressType
              )
            "
            @visibleChange="
              callCommonUtilFeildVisibleChange(
                mailLetterEditValidationForm.addressType
              )
            "
            :destroyTooltipOnHide="true"
          >
            <a-select
              v-model="modifymailLetterForm.addressType"
              style="width: 150px"
              :options="addressOptions"
              @change="onSelectAddressType()"
            >
            </a-select>
          </a-popover>
        </a-form-model-item>
      </a-col>
      <a-col :span="4">
        <!-- 郵遞區號 -->
        <a-form-model-item
          label=""
          prop="zipCode"
          style="margin-bottom: 0px"
          :has-feedback="
            callCommonUtilFeildFeedback(mailLetterEditValidationForm.zipCode)
          "
          :validateStatus="
            callCommonUtilFeildStatus(mailLetterEditValidationForm.zipCode)
          "
        >
          <a-popover
            placement="top"
            :content="
              callCommonUtilFeildMsg(mailLetterEditValidationForm.zipCode)
            "
            :trigger="
              callCommonUtilFeildTrigger(mailLetterEditValidationForm.zipCode)
            "
            :visible="
              callCommonUtilFeildHoverVisible(
                mailLetterEditValidationForm.zipCode
              )
            "
            @visibleChange="
              callCommonUtilFeildVisibleChange(
                mailLetterEditValidationForm.zipCode
              )
            "
            :destroyTooltipOnHide="true"
          >
            <a-input
              type="text"
              v-model="modifymailLetterForm.zipCode"
              :maxLength="5"
              @change="onSelectZipCode()"
              :disabled="addressTypeDisabled"
            />
          </a-popover>
        </a-form-model-item>
      </a-col>
      <a-col :span="12" :pull="1">
        <!-- 郵寄地址 -->
        <a-form-model-item
          label=""
          prop="address"
          style="margin-bottom: 0px"
          :has-feedback="
            callCommonUtilFeildFeedback(mailLetterEditValidationForm.address)
          "
          :validateStatus="
            callCommonUtilFeildStatus(mailLetterEditValidationForm.address)
          "
        >
          <a-popover
            placement="top"
            :content="
              callCommonUtilFeildMsg(mailLetterEditValidationForm.address)
            "
            :trigger="
              callCommonUtilFeildTrigger(mailLetterEditValidationForm.address)
            "
            :visible="
              callCommonUtilFeildHoverVisible(
                mailLetterEditValidationForm.address
              )
            "
            @visibleChange="
              callCommonUtilFeildVisibleChange(
                mailLetterEditValidationForm.address
              )
            "
            :destroyTooltipOnHide="true"
          >
            <a-input
              type="text"
              v-model="modifymailLetterForm.address"
              :maxLength="200"
              style="width: 380px"
              @change="onSelectAddress()"
              :disabled="addressTypeDisabled"
            />
          </a-popover>
        </a-form-model-item>
      </a-col>
    </a-row>
  </a-form-model>
</template>


<script src="./MailLetterEditForm.ts" lang="ts"></script>