<template>
  <a-form-model
    :label-col="{ span: 8 }"
    :wrapper-col="{ span: 12 }"
    :model="bancassuranceSettingForm"
    :rules="notiBancassuranceUpdateFormRules"
    ref="bancassuranceSettingForm"
  >
    <a-form-model-item
      :label="$t('notification_bancassuranceCode')"
      prop="bancassuranceId"
      style="margin-bottom: 0px"
      required
      :has-feedback="
        callCommonUtilFeildFeedback(
          notiBancassuranceValidationForm.bancassuranceId
        )
      "
      :validateStatus="
        callCommonUtilFeildStatus(
          notiBancassuranceValidationForm.bancassuranceId
        )
      "
    >
      <a-popover
        placement="top"
        :content="
          callCommonUtilFeildMsg(
            notiBancassuranceValidationForm.bancassuranceId
          )
        "
        :trigger="
          callCommonUtilFeildTrigger(
            notiBancassuranceValidationForm.bancassuranceId
          )
        "
        :visible="
          callCommonUtilFeildHoverVisible(
            notiBancassuranceValidationForm.bancassuranceId
          )
        "
        @visibleChange="
          callCommonUtilFeildVisibleChange(
            notiBancassuranceValidationForm.bancassuranceId
          )
        "
        :destroyTooltipOnHide="true"
      >
        <a-textarea
          type="text"
          :disabled="isEditing"
          v-model="bancassuranceSettingForm.bancassuranceId"
          :maxLength="10"
        />
      </a-popover>
    </a-form-model-item>

    <a-form-model-item
      :label="$t('notification_bancassuranceCode_description')"
      prop="description"
      style="margin-bottom: 0px"
      required
      :has-feedback="
        callCommonUtilFeildFeedback(notiBancassuranceValidationForm.description)
      "
      :validateStatus="
        callCommonUtilFeildStatus(notiBancassuranceValidationForm.description)
      "
    >
      <a-popover
        placement="top"
        :content="
          callCommonUtilFeildMsg(notiBancassuranceValidationForm.description)
        "
        :trigger="
          callCommonUtilFeildTrigger(
            notiBancassuranceValidationForm.description
          )
        "
        :visible="
          callCommonUtilFeildHoverVisible(
            notiBancassuranceValidationForm.description
          )
        "
        @visibleChange="
          callCommonUtilFeildVisibleChange(
            notiBancassuranceValidationForm.description
          )
        "
        :destroyTooltipOnHide="true"
      >
        <a-textarea
          type="text"
          v-model="bancassuranceSettingForm.description"
          :maxLength="100"
        />
      </a-popover>
    </a-form-model-item>
    <!-- 狀態 -->
    <a-form-model-item
      :label="$t('global_status')"
      style="margin-bottom: 0px"
      prop="status"
      required
      v-if="isEditing"
    >
      <a-select
        v-model="bancassuranceSettingForm.status"
        :options="selectStatusOptions"
        :placeholder="$t('roleSF_pleaseChoose')"
      >
        <!-- @change="onStatusChange" -->
      </a-select>
    </a-form-model-item>
  </a-form-model>
  <!-- </a-spin> -->
</template>
<script src="./NotiBancussuranceForm.ts" lang="ts"></script>
